version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Post-build phase started on `date`
      - echo Syncing files to S3...
      - aws s3 sync dist/ s3://banking-app-hackaton-frontend/ --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id E2A2U5E64JY2OG --paths "/*"
      - echo Deploy completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
