version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - echo "Current directory:" && pwd
      - echo "Directory contents:" && ls -la
      - echo "Frontend directory contents:" && ls -la frontend/
      - cd frontend
      - echo "Now in frontend directory:" && pwd
      - npm install
  
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - cd frontend
      
  build:
    commands:
      - echo Build started on `date`
      - cd frontend
      - npm run build
      - echo Build completed on `date`
      - echo "Dist directory contents:" && ls -la dist/
      
  post_build:
    commands:
      - echo Post-build phase started on `date`
      - cd frontend
      - echo Syncing files to S3...
      - aws s3 sync dist/ s3://banking-app-hackaton-frontend/ --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id E2A2U5E64JY2OG --paths "/*"
      - echo Deploy completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
