name: Deploy to AWS S3 and CloudFront (DISABLED)

# GitHub Actions deshabilitado - usando deploy manual exclusivamente
on:
  workflow_dispatch: # Solo ejecución manual desde GitHub UI
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Condición que nunca se cumple para deshabilitar completamente
    if: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build application
      run: |
        cd frontend
        npm run build
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Deploy to S3
      run: |
        cd frontend
        aws s3 sync dist/ s3://banking-app-hackaton-frontend/ --delete
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E2A2U5E64JY2OG --paths "/*"
        
    - name: Deployment complete
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🌐 Your app is available at:"
        echo "   S3: http://banking-app-hackaton-frontend.s3-website.us-west-2.amazonaws.com/"
        echo "   CloudFront: https://d1r8xtqjhx68zh.cloudfront.net/"
